### ISSUE TITLE
python3?

### ISSUE THREAD

**Issue by wmjie** [thomashuang/dbpy#1]
are there plans to support Python 3?

**Comment by whiteclover** [comment]
the mysqldb doesn't support python3+

try use pymysql adapter:

Install the extension with the following command::

```
$ easy_install pymysql
```

or alternatively if you have pip installed::

```
$ pip install pymysql
```

then:

```
config = {
        'passwd': 'test',
        'user': 'test',
        'host': 'localhost',
        'db': 'test',
        'max_idle' : 5*60
    }

db.setup(config,  minconn=5, maxconn=10,  
    adapter='pymysql', key='defalut', slave=False)
```

I had never test dbpy on python3, if have bug, please  feedback it  to me :).
just run the unittest  on python3+.

i will try to push it on pypi on  this weekday; so please git clone the last revision on github
